### ISSUE TITLE
Can't continue past word/day 267

### ISSUE THREAD

**Issue by pedroterzero** [DevangThakkar/wordle_archive#50]
It has been like that for me for a while. Is this intended behaviour?

**Comment by 12932** [comment]
I can't continue past 270 at the moment when I can play 271. I think it needs to be updated manually

**Comment by bobpaul** [comment]
This is intended behavior. It's an archive.

The game, just like wordle, looks at the local time and decides what games to show you based on your current date. The official wordle lets you play a single game based on today's date. The wordle archive lets you play all previous games, but not today's game and not any future games.

If you want to play more games, set the time on your computer to a date in the future. You might have to disconnect from wifi first so that the game loads from cache (if your time is wrong and your online it might show SSL errors). The same thing works with the real wordle.

**Comment by pedroterzero** [comment]
Never mind I thought it was further behind than it should have been but it's actually working correctly
